In [5]:
from collections import defaultdict
dict_ = defaultdict(int)

dict_['a'] += 1
dict_['a'] += 1

print(dict_['a'])
print(dict_['b'])

2
0


In [8]:
import numpy as np
import scipy.sparse as sp

a = sp.csr_matrix(np.array([[1, 2, 3, 4], [5, 6, 7, 8]]))
b= sp.csr_matrix(np.array([2, 1, 2, 1]))
a.multiply([1, 1, 1, 1]).toarray()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int64)

In [7]:
z = sp.csr_matrix([1,3,4])
z.toarray()

array([[1, 3, 4]], dtype=int64)

In [11]:
g = {'a': 1}
print(type(g.keys()))

<class 'dict_keys'>


In [15]:
g = {'a': 3, 'b': 100, 'v': 94}
items = g.items()
sorted(items, key=lambda x: x[1])

[('a', 3), ('v', 94), ('b', 100)]

In [60]:
import numpy as np
import scipy.sparse as sp

step = 7
b = np.arange(195)
b = sp.csr_matrix(np.reshape(b, newshape=(65, 3)))
#print(b.toarray())
len_ = b.shape[0]
indices = np.arange(len_)
np.random.shuffle(indices)

g = np.array_split(indices, len_/step)

for gg in g:
    print(b[gg].toarray())

[[120 121 122]
 [108 109 110]
 [ 84  85  86]
 [174 175 176]
 [183 184 185]
 [ 30  31  32]
 [150 151 152]
 [102 103 104]]
[[ 24  25  26]
 [171 172 173]
 [ 66  67  68]
 [ 78  79  80]
 [ 39  40  41]
 [117 118 119]
 [ 75  76  77]
 [ 81  82  83]]
[[  3   4   5]
 [  0   1   2]
 [114 115 116]
 [ 21  22  23]
 [153 154 155]
 [ 51  52  53]
 [141 142 143]]
[[135 136 137]
 [105 106 107]
 [ 96  97  98]
 [177 178 179]
 [ 27  28  29]
 [ 57  58  59]
 [147 148 149]]
[[ 72  73  74]
 [ 45  46  47]
 [ 12  13  14]
 [ 93  94  95]
 [156 157 158]
 [165 166 167]
 [126 127 128]]
[[ 42  43  44]
 [144 145 146]
 [ 15  16  17]
 [123 124 125]
 [  6   7   8]
 [ 33  34  35]
 [ 18  19  20]]
[[ 60  61  62]
 [ 87  88  89]
 [ 54  55  56]
 [ 99 100 101]
 [ 90  91  92]
 [162 163 164]
 [129 130 131]]
[[159 160 161]
 [192 193 194]
 [189 190 191]
 [ 69  70  71]
 [186 187 188]
 [  9  10  11]
 [132 133 134]]
[[ 63  64  65]
 [138 139 140]
 [180 181 182]
 [ 36  37  38]
 [168 169 170]
 [111 112 113]
 [ 48  49  50]]
